(cl:defpackage ms_pkg-srv
  (:use )
  (:export
   "FER_SERVICE"
   "<FER_SERVICE-REQUEST>"
   "FER_SERVICE-REQUEST"
   "<FER_SERVICE-RESPONSE>"
   "FER_SERVICE-RESPONSE"
   "LLMC_SERVICE"
   "<LLMC_SERVICE-REQUEST>"
   "LLMC_SERVICE-REQUEST"
   "<LLMC_SERVICE-RESPONSE>"
   "LLMC_SERVICE-RESPONSE"
   "STT_SERVICE"
   "<STT_SERVICE-REQUEST>"
   "STT_SERVICE-REQUEST"
   "<STT_SERVICE-RESPONSE>"
   "STT_SERVICE-RESPONSE"
   "TF_SERVICE"
   "<TF_SERVICE-REQUEST>"
   "TF_SERVICE-REQUEST"
   "<TF_SERVICE-RESPONSE>"
   "TF_SERVICE-RESPONSE"
  ))

