// Generated by gencpp from file ms_pkg/FER_service.msg
// DO NOT EDIT!


#ifndef MS_PKG_MESSAGE_FER_SERVICE_H
#define MS_PKG_MESSAGE_FER_SERVICE_H

#include <ros/service_traits.h>


#include <ms_pkg/FER_serviceRequest.h>
#include <ms_pkg/FER_serviceResponse.h>


namespace ms_pkg
{

struct FER_service
{

typedef FER_serviceRequest Request;
typedef FER_serviceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct FER_service
} // namespace ms_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ms_pkg::FER_service > {
  static const char* value()
  {
    return "db954e5de3aba73b237d07575e5cac28";
  }

  static const char* value(const ::ms_pkg::FER_service&) { return value(); }
};

template<>
struct DataType< ::ms_pkg::FER_service > {
  static const char* value()
  {
    return "ms_pkg/FER_service";
  }

  static const char* value(const ::ms_pkg::FER_service&) { return value(); }
};


// service_traits::MD5Sum< ::ms_pkg::FER_serviceRequest> should match
// service_traits::MD5Sum< ::ms_pkg::FER_service >
template<>
struct MD5Sum< ::ms_pkg::FER_serviceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ms_pkg::FER_service >::value();
  }
  static const char* value(const ::ms_pkg::FER_serviceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ms_pkg::FER_serviceRequest> should match
// service_traits::DataType< ::ms_pkg::FER_service >
template<>
struct DataType< ::ms_pkg::FER_serviceRequest>
{
  static const char* value()
  {
    return DataType< ::ms_pkg::FER_service >::value();
  }
  static const char* value(const ::ms_pkg::FER_serviceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ms_pkg::FER_serviceResponse> should match
// service_traits::MD5Sum< ::ms_pkg::FER_service >
template<>
struct MD5Sum< ::ms_pkg::FER_serviceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ms_pkg::FER_service >::value();
  }
  static const char* value(const ::ms_pkg::FER_serviceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ms_pkg::FER_serviceResponse> should match
// service_traits::DataType< ::ms_pkg::FER_service >
template<>
struct DataType< ::ms_pkg::FER_serviceResponse>
{
  static const char* value()
  {
    return DataType< ::ms_pkg::FER_service >::value();
  }
  static const char* value(const ::ms_pkg::FER_serviceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MS_PKG_MESSAGE_FER_SERVICE_H
