// Generated by gencpp from file ms_pkg/FER_serviceRequest.msg
// DO NOT EDIT!


#ifndef MS_PKG_MESSAGE_FER_SERVICEREQUEST_H
#define MS_PKG_MESSAGE_FER_SERVICEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ms_pkg
{
template <class ContainerAllocator>
struct FER_serviceRequest_
{
  typedef FER_serviceRequest_<ContainerAllocator> Type;

  FER_serviceRequest_()
    {
    }
  FER_serviceRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::ms_pkg::FER_serviceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ms_pkg::FER_serviceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct FER_serviceRequest_

typedef ::ms_pkg::FER_serviceRequest_<std::allocator<void> > FER_serviceRequest;

typedef boost::shared_ptr< ::ms_pkg::FER_serviceRequest > FER_serviceRequestPtr;
typedef boost::shared_ptr< ::ms_pkg::FER_serviceRequest const> FER_serviceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ms_pkg::FER_serviceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ms_pkg::FER_serviceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace ms_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ms_pkg::FER_serviceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ms_pkg::FER_serviceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ms_pkg::FER_serviceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ms_pkg::FER_serviceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ms_pkg::FER_serviceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ms_pkg::FER_serviceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ms_pkg::FER_serviceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::ms_pkg::FER_serviceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::ms_pkg::FER_serviceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ms_pkg/FER_serviceRequest";
  }

  static const char* value(const ::ms_pkg::FER_serviceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ms_pkg::FER_serviceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::ms_pkg::FER_serviceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ms_pkg::FER_serviceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FER_serviceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ms_pkg::FER_serviceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::ms_pkg::FER_serviceRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // MS_PKG_MESSAGE_FER_SERVICEREQUEST_H
