// Generated by gencpp from file ms_pkg/FER_serviceRequest.msg
// DO NOT EDIT!


#ifndef MS_PKG_MESSAGE_FER_SERVICEREQUEST_H
#define MS_PKG_MESSAGE_FER_SERVICEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/Image.h>

namespace ms_pkg
{
template <class ContainerAllocator>
struct FER_serviceRequest_
{
  typedef FER_serviceRequest_<ContainerAllocator> Type;

  FER_serviceRequest_()
    : img()  {
    }
  FER_serviceRequest_(const ContainerAllocator& _alloc)
    : img(_alloc)  {
  (void)_alloc;
    }



   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _img_type;
  _img_type img;





  typedef boost::shared_ptr< ::ms_pkg::FER_serviceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ms_pkg::FER_serviceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct FER_serviceRequest_

typedef ::ms_pkg::FER_serviceRequest_<std::allocator<void> > FER_serviceRequest;

typedef boost::shared_ptr< ::ms_pkg::FER_serviceRequest > FER_serviceRequestPtr;
typedef boost::shared_ptr< ::ms_pkg::FER_serviceRequest const> FER_serviceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ms_pkg::FER_serviceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ms_pkg::FER_serviceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ms_pkg::FER_serviceRequest_<ContainerAllocator1> & lhs, const ::ms_pkg::FER_serviceRequest_<ContainerAllocator2> & rhs)
{
  return lhs.img == rhs.img;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ms_pkg::FER_serviceRequest_<ContainerAllocator1> & lhs, const ::ms_pkg::FER_serviceRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ms_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ms_pkg::FER_serviceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ms_pkg::FER_serviceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ms_pkg::FER_serviceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ms_pkg::FER_serviceRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ms_pkg::FER_serviceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ms_pkg::FER_serviceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ms_pkg::FER_serviceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b4274f524cc812fc54ca8ebeeda2deb2";
  }

  static const char* value(const ::ms_pkg::FER_serviceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb4274f524cc812fcULL;
  static const uint64_t static_value2 = 0x54ca8ebeeda2deb2ULL;
};

template<class ContainerAllocator>
struct DataType< ::ms_pkg::FER_serviceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ms_pkg/FER_serviceRequest";
  }

  static const char* value(const ::ms_pkg::FER_serviceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ms_pkg::FER_serviceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensor_msgs/Image img\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/Image\n"
"# This message contains an uncompressed image\n"
"# (0, 0) is at top-left corner of image\n"
"#\n"
"\n"
"Header header        # Header timestamp should be acquisition time of image\n"
"                     # Header frame_id should be optical frame of camera\n"
"                     # origin of frame should be optical center of camera\n"
"                     # +x should point to the right in the image\n"
"                     # +y should point down in the image\n"
"                     # +z should point into to plane of the image\n"
"                     # If the frame_id here and the frame_id of the CameraInfo\n"
"                     # message associated with the image conflict\n"
"                     # the behavior is undefined\n"
"\n"
"uint32 height         # image height, that is, number of rows\n"
"uint32 width          # image width, that is, number of columns\n"
"\n"
"# The legal values for encoding are in file src/image_encodings.cpp\n"
"# If you want to standardize a new string format, join\n"
"# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n"
"\n"
"string encoding       # Encoding of pixels -- channel meaning, ordering, size\n"
"                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n"
"\n"
"uint8 is_bigendian    # is this data bigendian?\n"
"uint32 step           # Full row length in bytes\n"
"uint8[] data          # actual matrix data, size is (step * rows)\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::ms_pkg::FER_serviceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ms_pkg::FER_serviceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.img);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FER_serviceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ms_pkg::FER_serviceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ms_pkg::FER_serviceRequest_<ContainerAllocator>& v)
  {
    s << indent << "img: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.img);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MS_PKG_MESSAGE_FER_SERVICEREQUEST_H
