// Generated by gencpp from file ms_pkg/Greeting_service.msg
// DO NOT EDIT!


#ifndef MS_PKG_MESSAGE_GREETING_SERVICE_H
#define MS_PKG_MESSAGE_GREETING_SERVICE_H

#include <ros/service_traits.h>


#include <ms_pkg/Greeting_serviceRequest.h>
#include <ms_pkg/Greeting_serviceResponse.h>


namespace ms_pkg
{

struct Greeting_service
{

typedef Greeting_serviceRequest Request;
typedef Greeting_serviceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Greeting_service
} // namespace ms_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ms_pkg::Greeting_service > {
  static const char* value()
  {
    return "f58cc1930ee734da0da3606508759ab9";
  }

  static const char* value(const ::ms_pkg::Greeting_service&) { return value(); }
};

template<>
struct DataType< ::ms_pkg::Greeting_service > {
  static const char* value()
  {
    return "ms_pkg/Greeting_service";
  }

  static const char* value(const ::ms_pkg::Greeting_service&) { return value(); }
};


// service_traits::MD5Sum< ::ms_pkg::Greeting_serviceRequest> should match
// service_traits::MD5Sum< ::ms_pkg::Greeting_service >
template<>
struct MD5Sum< ::ms_pkg::Greeting_serviceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ms_pkg::Greeting_service >::value();
  }
  static const char* value(const ::ms_pkg::Greeting_serviceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ms_pkg::Greeting_serviceRequest> should match
// service_traits::DataType< ::ms_pkg::Greeting_service >
template<>
struct DataType< ::ms_pkg::Greeting_serviceRequest>
{
  static const char* value()
  {
    return DataType< ::ms_pkg::Greeting_service >::value();
  }
  static const char* value(const ::ms_pkg::Greeting_serviceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ms_pkg::Greeting_serviceResponse> should match
// service_traits::MD5Sum< ::ms_pkg::Greeting_service >
template<>
struct MD5Sum< ::ms_pkg::Greeting_serviceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ms_pkg::Greeting_service >::value();
  }
  static const char* value(const ::ms_pkg::Greeting_serviceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ms_pkg::Greeting_serviceResponse> should match
// service_traits::DataType< ::ms_pkg::Greeting_service >
template<>
struct DataType< ::ms_pkg::Greeting_serviceResponse>
{
  static const char* value()
  {
    return DataType< ::ms_pkg::Greeting_service >::value();
  }
  static const char* value(const ::ms_pkg::Greeting_serviceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MS_PKG_MESSAGE_GREETING_SERVICE_H
