// Generated by gencpp from file ms_pkg/IC_service.msg
// DO NOT EDIT!


#ifndef MS_PKG_MESSAGE_IC_SERVICE_H
#define MS_PKG_MESSAGE_IC_SERVICE_H

#include <ros/service_traits.h>


#include <ms_pkg/IC_serviceRequest.h>
#include <ms_pkg/IC_serviceResponse.h>


namespace ms_pkg
{

struct IC_service
{

typedef IC_serviceRequest Request;
typedef IC_serviceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct IC_service
} // namespace ms_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ms_pkg::IC_service > {
  static const char* value()
  {
    return "4414c67819626a1b8e0f043a9a0d6c9a";
  }

  static const char* value(const ::ms_pkg::IC_service&) { return value(); }
};

template<>
struct DataType< ::ms_pkg::IC_service > {
  static const char* value()
  {
    return "ms_pkg/IC_service";
  }

  static const char* value(const ::ms_pkg::IC_service&) { return value(); }
};


// service_traits::MD5Sum< ::ms_pkg::IC_serviceRequest> should match
// service_traits::MD5Sum< ::ms_pkg::IC_service >
template<>
struct MD5Sum< ::ms_pkg::IC_serviceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ms_pkg::IC_service >::value();
  }
  static const char* value(const ::ms_pkg::IC_serviceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ms_pkg::IC_serviceRequest> should match
// service_traits::DataType< ::ms_pkg::IC_service >
template<>
struct DataType< ::ms_pkg::IC_serviceRequest>
{
  static const char* value()
  {
    return DataType< ::ms_pkg::IC_service >::value();
  }
  static const char* value(const ::ms_pkg::IC_serviceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ms_pkg::IC_serviceResponse> should match
// service_traits::MD5Sum< ::ms_pkg::IC_service >
template<>
struct MD5Sum< ::ms_pkg::IC_serviceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ms_pkg::IC_service >::value();
  }
  static const char* value(const ::ms_pkg::IC_serviceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ms_pkg::IC_serviceResponse> should match
// service_traits::DataType< ::ms_pkg::IC_service >
template<>
struct DataType< ::ms_pkg::IC_serviceResponse>
{
  static const char* value()
  {
    return DataType< ::ms_pkg::IC_service >::value();
  }
  static const char* value(const ::ms_pkg::IC_serviceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MS_PKG_MESSAGE_IC_SERVICE_H
