// Generated by gencpp from file ms_pkg/LLMC_service.msg
// DO NOT EDIT!


#ifndef MS_PKG_MESSAGE_LLMC_SERVICE_H
#define MS_PKG_MESSAGE_LLMC_SERVICE_H

#include <ros/service_traits.h>


#include <ms_pkg/LLMC_serviceRequest.h>
#include <ms_pkg/LLMC_serviceResponse.h>


namespace ms_pkg
{

struct LLMC_service
{

typedef LLMC_serviceRequest Request;
typedef LLMC_serviceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LLMC_service
} // namespace ms_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ms_pkg::LLMC_service > {
  static const char* value()
  {
    return "06454699f37ee48508b43358c9d71b7e";
  }

  static const char* value(const ::ms_pkg::LLMC_service&) { return value(); }
};

template<>
struct DataType< ::ms_pkg::LLMC_service > {
  static const char* value()
  {
    return "ms_pkg/LLMC_service";
  }

  static const char* value(const ::ms_pkg::LLMC_service&) { return value(); }
};


// service_traits::MD5Sum< ::ms_pkg::LLMC_serviceRequest> should match
// service_traits::MD5Sum< ::ms_pkg::LLMC_service >
template<>
struct MD5Sum< ::ms_pkg::LLMC_serviceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ms_pkg::LLMC_service >::value();
  }
  static const char* value(const ::ms_pkg::LLMC_serviceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ms_pkg::LLMC_serviceRequest> should match
// service_traits::DataType< ::ms_pkg::LLMC_service >
template<>
struct DataType< ::ms_pkg::LLMC_serviceRequest>
{
  static const char* value()
  {
    return DataType< ::ms_pkg::LLMC_service >::value();
  }
  static const char* value(const ::ms_pkg::LLMC_serviceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ms_pkg::LLMC_serviceResponse> should match
// service_traits::MD5Sum< ::ms_pkg::LLMC_service >
template<>
struct MD5Sum< ::ms_pkg::LLMC_serviceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ms_pkg::LLMC_service >::value();
  }
  static const char* value(const ::ms_pkg::LLMC_serviceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ms_pkg::LLMC_serviceResponse> should match
// service_traits::DataType< ::ms_pkg::LLMC_service >
template<>
struct DataType< ::ms_pkg::LLMC_serviceResponse>
{
  static const char* value()
  {
    return DataType< ::ms_pkg::LLMC_service >::value();
  }
  static const char* value(const ::ms_pkg::LLMC_serviceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MS_PKG_MESSAGE_LLMC_SERVICE_H
