// Generated by gencpp from file ms_pkg/LLMC_serviceRequest.msg
// DO NOT EDIT!


#ifndef MS_PKG_MESSAGE_LLMC_SERVICEREQUEST_H
#define MS_PKG_MESSAGE_LLMC_SERVICEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ms_pkg
{
template <class ContainerAllocator>
struct LLMC_serviceRequest_
{
  typedef LLMC_serviceRequest_<ContainerAllocator> Type;

  LLMC_serviceRequest_()
    : user_text()  {
    }
  LLMC_serviceRequest_(const ContainerAllocator& _alloc)
    : user_text(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _user_text_type;
  _user_text_type user_text;





  typedef boost::shared_ptr< ::ms_pkg::LLMC_serviceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ms_pkg::LLMC_serviceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct LLMC_serviceRequest_

typedef ::ms_pkg::LLMC_serviceRequest_<std::allocator<void> > LLMC_serviceRequest;

typedef boost::shared_ptr< ::ms_pkg::LLMC_serviceRequest > LLMC_serviceRequestPtr;
typedef boost::shared_ptr< ::ms_pkg::LLMC_serviceRequest const> LLMC_serviceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ms_pkg::LLMC_serviceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ms_pkg::LLMC_serviceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ms_pkg::LLMC_serviceRequest_<ContainerAllocator1> & lhs, const ::ms_pkg::LLMC_serviceRequest_<ContainerAllocator2> & rhs)
{
  return lhs.user_text == rhs.user_text;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ms_pkg::LLMC_serviceRequest_<ContainerAllocator1> & lhs, const ::ms_pkg::LLMC_serviceRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ms_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ms_pkg::LLMC_serviceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ms_pkg::LLMC_serviceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ms_pkg::LLMC_serviceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ms_pkg::LLMC_serviceRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ms_pkg::LLMC_serviceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ms_pkg::LLMC_serviceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ms_pkg::LLMC_serviceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2e0d533caaa6c5a0bfe0e685b3eecbc0";
  }

  static const char* value(const ::ms_pkg::LLMC_serviceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2e0d533caaa6c5a0ULL;
  static const uint64_t static_value2 = 0xbfe0e685b3eecbc0ULL;
};

template<class ContainerAllocator>
struct DataType< ::ms_pkg::LLMC_serviceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ms_pkg/LLMC_serviceRequest";
  }

  static const char* value(const ::ms_pkg::LLMC_serviceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ms_pkg::LLMC_serviceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string user_text\n"
;
  }

  static const char* value(const ::ms_pkg::LLMC_serviceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ms_pkg::LLMC_serviceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.user_text);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LLMC_serviceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ms_pkg::LLMC_serviceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ms_pkg::LLMC_serviceRequest_<ContainerAllocator>& v)
  {
    s << indent << "user_text: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.user_text);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MS_PKG_MESSAGE_LLMC_SERVICEREQUEST_H
