// Generated by gencpp from file ms_pkg/STT_service.msg
// DO NOT EDIT!


#ifndef MS_PKG_MESSAGE_STT_SERVICE_H
#define MS_PKG_MESSAGE_STT_SERVICE_H

#include <ros/service_traits.h>


#include <ms_pkg/STT_serviceRequest.h>
#include <ms_pkg/STT_serviceResponse.h>


namespace ms_pkg
{

struct STT_service
{

typedef STT_serviceRequest Request;
typedef STT_serviceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct STT_service
} // namespace ms_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ms_pkg::STT_service > {
  static const char* value()
  {
    return "0b7e0c9192d9ca1d34c68e21095b2124";
  }

  static const char* value(const ::ms_pkg::STT_service&) { return value(); }
};

template<>
struct DataType< ::ms_pkg::STT_service > {
  static const char* value()
  {
    return "ms_pkg/STT_service";
  }

  static const char* value(const ::ms_pkg::STT_service&) { return value(); }
};


// service_traits::MD5Sum< ::ms_pkg::STT_serviceRequest> should match
// service_traits::MD5Sum< ::ms_pkg::STT_service >
template<>
struct MD5Sum< ::ms_pkg::STT_serviceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ms_pkg::STT_service >::value();
  }
  static const char* value(const ::ms_pkg::STT_serviceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ms_pkg::STT_serviceRequest> should match
// service_traits::DataType< ::ms_pkg::STT_service >
template<>
struct DataType< ::ms_pkg::STT_serviceRequest>
{
  static const char* value()
  {
    return DataType< ::ms_pkg::STT_service >::value();
  }
  static const char* value(const ::ms_pkg::STT_serviceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ms_pkg::STT_serviceResponse> should match
// service_traits::MD5Sum< ::ms_pkg::STT_service >
template<>
struct MD5Sum< ::ms_pkg::STT_serviceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ms_pkg::STT_service >::value();
  }
  static const char* value(const ::ms_pkg::STT_serviceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ms_pkg::STT_serviceResponse> should match
// service_traits::DataType< ::ms_pkg::STT_service >
template<>
struct DataType< ::ms_pkg::STT_serviceResponse>
{
  static const char* value()
  {
    return DataType< ::ms_pkg::STT_service >::value();
  }
  static const char* value(const ::ms_pkg::STT_serviceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MS_PKG_MESSAGE_STT_SERVICE_H
