// Generated by gencpp from file ms_pkg/STT_serviceRequest.msg
// DO NOT EDIT!


#ifndef MS_PKG_MESSAGE_STT_SERVICEREQUEST_H
#define MS_PKG_MESSAGE_STT_SERVICEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ms_pkg
{
template <class ContainerAllocator>
struct STT_serviceRequest_
{
  typedef STT_serviceRequest_<ContainerAllocator> Type;

  STT_serviceRequest_()
    : file_path()  {
    }
  STT_serviceRequest_(const ContainerAllocator& _alloc)
    : file_path(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _file_path_type;
  _file_path_type file_path;





  typedef boost::shared_ptr< ::ms_pkg::STT_serviceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ms_pkg::STT_serviceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct STT_serviceRequest_

typedef ::ms_pkg::STT_serviceRequest_<std::allocator<void> > STT_serviceRequest;

typedef boost::shared_ptr< ::ms_pkg::STT_serviceRequest > STT_serviceRequestPtr;
typedef boost::shared_ptr< ::ms_pkg::STT_serviceRequest const> STT_serviceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ms_pkg::STT_serviceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ms_pkg::STT_serviceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ms_pkg::STT_serviceRequest_<ContainerAllocator1> & lhs, const ::ms_pkg::STT_serviceRequest_<ContainerAllocator2> & rhs)
{
  return lhs.file_path == rhs.file_path;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ms_pkg::STT_serviceRequest_<ContainerAllocator1> & lhs, const ::ms_pkg::STT_serviceRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ms_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ms_pkg::STT_serviceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ms_pkg::STT_serviceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ms_pkg::STT_serviceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ms_pkg::STT_serviceRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ms_pkg::STT_serviceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ms_pkg::STT_serviceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ms_pkg::STT_serviceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a1f82596372c52a517e1fe32d1e998e8";
  }

  static const char* value(const ::ms_pkg::STT_serviceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa1f82596372c52a5ULL;
  static const uint64_t static_value2 = 0x17e1fe32d1e998e8ULL;
};

template<class ContainerAllocator>
struct DataType< ::ms_pkg::STT_serviceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ms_pkg/STT_serviceRequest";
  }

  static const char* value(const ::ms_pkg::STT_serviceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ms_pkg::STT_serviceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string file_path\n"
;
  }

  static const char* value(const ::ms_pkg::STT_serviceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ms_pkg::STT_serviceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.file_path);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct STT_serviceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ms_pkg::STT_serviceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ms_pkg::STT_serviceRequest_<ContainerAllocator>& v)
  {
    s << indent << "file_path: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.file_path);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MS_PKG_MESSAGE_STT_SERVICEREQUEST_H
