// Generated by gencpp from file ms_pkg/TTS_serviceResponse.msg
// DO NOT EDIT!


#ifndef MS_PKG_MESSAGE_TTS_SERVICERESPONSE_H
#define MS_PKG_MESSAGE_TTS_SERVICERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ms_pkg
{
template <class ContainerAllocator>
struct TTS_serviceResponse_
{
  typedef TTS_serviceResponse_<ContainerAllocator> Type;

  TTS_serviceResponse_()
    : result(0)  {
    }
  TTS_serviceResponse_(const ContainerAllocator& _alloc)
    : result(0)  {
  (void)_alloc;
    }



   typedef int8_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::ms_pkg::TTS_serviceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ms_pkg::TTS_serviceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct TTS_serviceResponse_

typedef ::ms_pkg::TTS_serviceResponse_<std::allocator<void> > TTS_serviceResponse;

typedef boost::shared_ptr< ::ms_pkg::TTS_serviceResponse > TTS_serviceResponsePtr;
typedef boost::shared_ptr< ::ms_pkg::TTS_serviceResponse const> TTS_serviceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ms_pkg::TTS_serviceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ms_pkg::TTS_serviceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ms_pkg::TTS_serviceResponse_<ContainerAllocator1> & lhs, const ::ms_pkg::TTS_serviceResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ms_pkg::TTS_serviceResponse_<ContainerAllocator1> & lhs, const ::ms_pkg::TTS_serviceResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ms_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ms_pkg::TTS_serviceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ms_pkg::TTS_serviceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ms_pkg::TTS_serviceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ms_pkg::TTS_serviceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ms_pkg::TTS_serviceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ms_pkg::TTS_serviceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ms_pkg::TTS_serviceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4414c67819626a1b8e0f043a9a0d6c9a";
  }

  static const char* value(const ::ms_pkg::TTS_serviceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4414c67819626a1bULL;
  static const uint64_t static_value2 = 0x8e0f043a9a0d6c9aULL;
};

template<class ContainerAllocator>
struct DataType< ::ms_pkg::TTS_serviceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ms_pkg/TTS_serviceResponse";
  }

  static const char* value(const ::ms_pkg::TTS_serviceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ms_pkg::TTS_serviceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 result\n"
;
  }

  static const char* value(const ::ms_pkg::TTS_serviceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ms_pkg::TTS_serviceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TTS_serviceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ms_pkg::TTS_serviceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ms_pkg::TTS_serviceResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<int8_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MS_PKG_MESSAGE_TTS_SERVICERESPONSE_H
